config/routes.rb
Keepintouch::Application.routes.draw do

	root :to => "pages#home"

	match '/home', :to => 'pages#home'
	match '/login', :to => 'pages#login'
	match '/linkedin', :to => 'auth#index'
	match '/auth/callback', :to => 'auth#callback'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_controller.rb
require 'rubygems'
require 'linkedin'

class AuthController < ApplicationController

  def index
    # get your api keys at https://www.linkedin.com/secure/developer
    client = LinkedIn::Client.new("8oaf3pfy4ill", "xaJ1ydaP7DvhVc5O")
    request_token = client.request_token(:oauth_callback => 
                                      "http://#{request.host_with_port}/auth/callback")
    session[:rtoken] = request_token.token
    session[:rsecret] = request_token.secret

    redirect_to client.request_token.authorize_url

  end

  def callback
    client = LinkedIn::Client.new("8oaf3pfy4ill", "xaJ1ydaP7DvhVc5O")
    if session[:atoken].nil?
      pin = params[:oauth_verifier]
      atoken, asecret = client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      session[:atoken] = atoken
      session[:asecret] = asecret
    else
      client.authorize_from_access(session[:atoken], session[:asecret])
    end
    @profile = client.profile
    @connections = client.connections
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keepintouch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/callback.html.erb
<h1>You're logged in!</h1>

app/views/pages/home.html.erb
<h1>Welcome!</h1>
<p><%= link_to "Login page", login_path %>

app/views/pages/login.html.erb
<h1>Login</h1>
<%= link_to "Click here to login with Linkedin", linkedin_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>